---

- hosts: localhost
  vars:
    home: /host/home
    configs:
      - "{{ home }}/.zprofile"
      - "{{ home }}/.bashrc"

  tasks:
    - lineinfile:
        dest: "{{ item }}"
        state: present
        create: yes
        line: "set -o vi"
      loop: "{{ configs }}"

    - lineinfile:
        dest: "{{ item }}"
        state: present
        create: true
        regexp: "fixssh"
        line: "alias fixssh='eval $(tmux showenv -s SSH_AUTH_SOCK)'"
      loop: "{{ configs }}"

    - lineinfile:
        dest: "{{ item }}"
        state: present
        create: yes
        line: |
          export PS1='$(__git_ps1) \W\$ '
      loop: "{{ configs }}"

    - copy:
        src: gitconfig
        dest: "{{ home }}/.gitconfig"
